### ISSUE TITLE
spurious NullPointerException in ArrayByteBufferPool.release()

### ISSUE THREAD

**Issue by loetifuss** [eclipse/jetty.project#12623]
**Jetty version(s)**
Jetty 12.0.15

**Jetty Environment**
core

**Java version/vendor** `(use: java -version)`
JDK 17.0.12

**OS type/version**
RedHat Linux

**Description**
After upgrading from Jetty 9 to 12 we're experiencing intermittent NullPointerExceptions, mostly from EventSourceSevlet.
Jetty is running embedded in an OSGI environment.

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.getByteBuffer()" because "buffer" is null
	at org.eclipse.jetty.io.ArrayByteBufferPool.release(ArrayByteBufferPool.java:281)
	at org.eclipse.jetty.io.ArrayByteBufferPool$Buffer.release(ArrayByteBufferPool.java:653)
	at org.eclipse.jetty.io.ArrayByteBufferPool.removeAndRelease(ArrayByteBufferPool.java:244)
	at org.eclipse.jetty.ee10.servlet.HttpOutput.lockedReleaseBuffer(HttpOutput.java:605)
	at org.eclipse.jetty.ee10.servlet.HttpOutput.onWriteComplete(HttpOutput.java:226)
	at org.eclipse.jetty.ee10.servlet.HttpOutput.flush(HttpOutput.java:690)
	at org.eclipse.jetty.ee10.servlet.ServletApiResponse.flushBuffer(ServletApiResponse.java:405)
	at org.eclipse.jetty.ee10.servlets.EventSourceServlet$EventSourceEmitter.flush(EventSourceServlet.java:223)
	at org.eclipse.jetty.ee10.servlets.EventSourceServlet$EventSourceEmitter.data(EventSourceServlet.java:169)
```

**How to reproduce?**

Not yet reproducible, seems to occur mostly during daytime under load:

![image](https://github.com/user-attachments/assets/d7cdacda-917a-4703-9c88-97c1cc4e524f)

**Comment by joakime** [comment]
Upgrade to Jetty 12.0.15 at least, and try again.
This is fixed already.

**Comment by loetifuss** [comment]
Upgrading to Jetty 12.0.15 didn't help. Still seeing these errors frequently.

**Comment by gregw** [comment]
@loetifuss Can you tell us anything else about the requests and responses?   How are they read/generated? Are they big/small? Are they json/binary/???   Are you writing async or blocking?   When it is not from the EventSourceServlet, where is it from?

**Comment by gregw** [comment]
@lorban My reading of the code is that the entry can only have a null buffer if it has not yet been enabled, or was enabled but the pool was terminated

@loetifuss Can you also tell us if you configure your buffer pool? If so then how?

**Comment by lorban** [comment]
@gregw your reading is right if the entry was a `ConcurrentEntry` instance, but I'm wondering if that instance wasn't a `QueuedEntry`?

**Comment by lorban** [comment]
Duplicated by #12790
