### ISSUE TITLE
Enable websocket client backpressure API

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/jetty.project#13224]
**Jetty version(s)**
12.0.20

**Enhancement Description**
`session.demand()` is not compatible with a backpressure like API because active sink is an internal state and when null demand is automatically called (instead of letting the caller handle it) so long story short it is very hard (almost impossible with being plugged very low) to not use auto demanding listener.

Reference: org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandler#acceptFrame

the listener implementation only override `onopen`, `onclose` and `onframe` implementing `Session.Listener`. This doesn't seem to think it handles text/binary messages so autodemands implicitly which is wrong when these messages are handled.

edit: workaround is to use all methods instead of the frame callback (but this one is neat cause it has the callback parameter compared to text callbacks)

**Comment by sbordet** [comment]
@rmannibucau this is fixed in 12.1.x after #11307.

Can you try it out and verify that it works for you?

**Comment by rmannibucau** [comment]
Hi @sbordet looks better, the only thing I'm still missing is the equivalent of `org.eclipse.jetty.io.content.ContentSourcePublisher.ActiveSubscription#request` where you can "stack" demands but at least I can make my code working handling the "stacking" on my hand now.

**Comment by sbordet** [comment]
What do you mean by "stack demands" exactly?

**Comment by rmannibucau** [comment]
@sbordet like Flow API of the JDK or reactivestreams, i want to be able to demand a "count", typically I know I'll get 2 messages so i do "request(2)" which lead to 2 demands. For jetty it would be a kind of switch to autodemand mode until exhaustion of the counter exactly as in the ActiveSubscription implementation for the http content.

**Comment by sbordet** [comment]
Ah, no, we don't support that, and we likely won't.

**Comment by rmannibucau** [comment]
i'd like to keep it open since it is a real need and workarounds are not very satisfying IMHO

**Comment by lachlan-roberts** [comment]
@rmannibucau there has been a change in `12.1.x`, that it is no longer possible to use  `onWebSocketFrame` in combination with the message handlers `onWebSocketBinary`, `onWebSocketText`, etc.

If you use `onWebSocketFrame`, a call to `session.demand()` is equivalent to demanding a single frame. 

If you are using any other combination of the message handlers, a call to `session.demand()` is essentially demanding that frames can be processed until the WebSocket Listener can be invoked again. This may auto-demand non-final frames until the complete message is accumulated and the application can be invoked (if you are using the whole message handlers).
