### ISSUE TITLE
java.lang.IllegalStateException is thrown when using CompressionHandler and a custom Handler that uses BufferedOutputStream

### ISSUE THREAD

**Issue by patel-act** [eclipse/jetty.project#14122]
**Jetty version(s)**
Jetty 12.1.4

**Jetty Environment**
core

**HTTP version**
HTTP 1.1

**Java version/vendor** `(use: java -version)`
21

**Description**

My server code is having a custom Handler that uses Response.asBufferedOutputStream() to return an "Hello World" html page. In addition, I am also using CompressionHandler in the handler chain. When I access my server using browser, I am getting following exception on the server and the browser displays a blank page.

```
java.lang.IllegalStateException: last already written
	at org.eclipse.jetty.server.internal.HttpChannelState.lockedStreamSend(HttpChannelState.java:580)
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelResponse.write(HttpChannelState.java:1319)
	at org.eclipse.jetty.compression.EncoderSink$EncodeBufferCallback.write(EncoderSink.java:123)
	at org.eclipse.jetty.compression.EncoderSink$EncodeBufferCallback.process(EncoderSink.java:103)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:377)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:354)
	at org.eclipse.jetty.compression.EncoderSink.write(EncoderSink.java:39)
	at org.eclipse.jetty.compression.server.internal.CompressionResponse.write(CompressionResponse.java:147)
	at org.eclipse.jetty.io.content.BufferedContentSink.flush(BufferedContentSink.java:127)
	at org.eclipse.jetty.io.content.BufferedContentSink.write(BufferedContentSink.java:101)
	at org.eclipse.jetty.io.content.ContentSinkOutputStream.close(ContentSinkOutputStream.java:101)
	at org.eclipse.jetty.io.content.ContentSinkOutputStream.close(ContentSinkOutputStream.java:83)
	at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:435)
	at java.base/sun.nio.cs.StreamEncoder.lockedClose(StreamEncoder.java:237)
	at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:222)
	at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:266)
	at java.base/java.io.BufferedWriter.implClose(BufferedWriter.java:398)
	at java.base/java.io.BufferedWriter.close(BufferedWriter.java:380)
	at java.base/java.io.PrintWriter.implClose(PrintWriter.java:457)
	at java.base/java.io.PrintWriter.close(PrintWriter.java:449)
	at com.actenum.cx.jetty.JettyExample$1.handle(JettyExample.java:37)
	at org.eclipse.jetty.compression.server.CompressionHandler.handle(CompressionHandler.java:346)
	at org.eclipse.jetty.server.Server.handle(Server.java:197)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:720)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:412)
	at org.eclipse.jetty.server.internal.HttpConnection$FillableCallback.succeeded(HttpConnection.java:1810)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:54)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:492)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.epcRunTask(AdaptiveExecutionStrategy.java:428)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:401)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:255)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:204)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:317)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:1009)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1239)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1194)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**How to reproduce?**

To reproduce the problem, I am executing the following code and pointing the browser to http://localhost:9900

```
import java.io.OutputStream;
import java.io.PrintWriter;

import org.eclipse.jetty.compression.server.CompressionHandler;
import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.Response;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.util.Callback;

public class JettyExample {

	public static void main(String[] args) throws Exception {
		Handler helloWorldHandler = new Handler.Abstract() {
			@Override
			public boolean handle(Request req, Response res, Callback callback) {

				String body = """
						<!DOCTYPE html>
						<html>
						<head>
						    <title>Hello World</title>
						</head>
						<body>
						    <h1>Hello World!</h1>
						</body>
						</html>
						""";

				try (OutputStream os = Response.asBufferedOutputStream(req, res); PrintWriter pw = new PrintWriter(os)) {
					pw.write(body);
					pw.flush();
					callback.succeeded();
				} catch (Throwable t) {
					callback.failed(t);
					t.printStackTrace();
				}

				return true;
			}
		};

		Server server = new Server();
		ServerConnector connector = new ServerConnector(server);
		connector.setPort(9900);
		server.addConnector(connector);
		
		// Compression handler
		CompressionHandler compressionHandler = new CompressionHandler();
		compressionHandler.setHandler(helloWorldHandler);
		server.setHandler(compressionHandler);

		server.start();
		server.join();
	}
}
```

**Additional Information**

Any one of the following 3 code changes would prevent the exception and the html page will be displayed in the browser.

1) Remove "callback.succeeded()" call. But this call is needed according to javadoc of public boolean handle(Request req, Response res, Callback callback)  method
2) Replace CompressionHandler with GzipHandler. But GzipHandler is deprecated in Jetty 12.1.4
		GzipHandler gzipHandler = new GzipHandler();
		gzipHandler.setHandler(helloWorldHandler);
		server.setHandler(gzipHandler);
3) Do not use BufferedOutputStream, instead write the response using ByteBuffer:
		res.setStatus(200);
		res.getHeaders().put(HttpHeader.CONTENT_TYPE, "text/html;charset=utf-8");
		res.write(true, ByteBuffer.wrap(body.getBytes(StandardCharsets.UTF_8)), callback);

**Comment by joakime** [comment]
You didn't set the `Content-Type` when using the `BufferedOutputStream`.

Ultimately, I think this was fixed recently in the upcoming 12.1.5 release.
I'll see if I can find the PR for that change ...

**Comment by patel-act** [comment]
Thanks for pointing that out. I added `Content-Type` header in the response when using `BufferedOutputStream`, but still getting the same result.

`	res.getHeaders().put(HttpHeader.CONTENT_TYPE, "text/html;charset=utf-8");`

Please let me know if you find that PR.

**Comment by joakime** [comment]
I think it was fixed with ...

* #13694

**Comment by patel-act** [comment]
That fix was in 12.1.3. However I am having this issue in 12.1.4. Could this be a different issue ?

**Comment by lorban** [comment]
Move the `callback.succeeded()` call outside the try/catch block, just before returning true. But make sure you do not succeed the callback if you already failed it in the catch block!

This happens because succeeding the callback must be the last thing you do, but since you're using a try-with-resource block, after succeeding the callback the output stream gets closed which requires doing the last send. Since that happens after the callback got succeeded, you get that failure.

**Comment by joakime** [comment]
@lorban seems like the code should be ...

``` java
try (OutputStream os = Response.asBufferedOutputStream(req, res, callback); 
    PrintWriter pw = new PrintWriter(os)) {
    pw.write(body);
    pw.flush();
} catch (Throwable t) {
    t.printStackTrace();
}
```

Letting the `Response.asBufferedOutputStream` handle the callback success/failure.

But then we couldn't use consecutive output streams.

Thinking about it some more, since this is a `PrintWriter`, the user has to check the `PrintWriter` failure APIs to know if it succeeded or failed, as those APIs do not throw exceptions.  Making the passing of callback to `Response.asBufferedOutputStream()` moot.

Eg: replace the `pw.flush()` with [`pw.checkError()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/PrintWriter.html#checkError()).

So ...

``` java
try (OutputStream os = Response.asBufferedOutputStream(req, res); 
    PrintWriter pw = new PrintWriter(os)) {
    pw.write(body);
    if (pw.checkError()) {
        // fail callback
    }
} catch (Throwable t) {
    // fail callback
    t.printStackTrace();
}
// succeed callback if not failed already
```

**Comment by patel-act** [comment]
Thank you @lorban and @joakime. Moving callback.succeed() after the try-catch block fixes the problem! Also I should be calling PrintWriter checkError() to properly handle the error.
