### ISSUE TITLE
GzipHandler generated ETag suffix has problems with If-Match header logic

### ISSUE THREAD

**Issue by blop** [eclipse/jetty.project#1416]
There is an issue in Jetty 9.4.3.v20170317.

When using the GzipHandler, ETag are suffixed with a '--gzip'.
When the client is using either If-Match or If-None-Match headers, GzipHandler should cut that suffix so that the ETag is back to it's original value further in the handling chain.

It's currently only handled for If-None-Match : 
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/gzip/GzipHandler.java#L538

Handling should be added for If-Match as well, for the exact same reason.

Thanks

**Comment by oliver-steinbrecher** [comment]
We do have the same issue . Can someone please confirm / mark this an official bug ?

**Comment by gregw** [comment]
I've just pushed a fix for this, but I will leave the issue open as I have not done a unit test.

**Comment by tobilarscheid** [comment]
In which release will this be?

**Comment by gregw** [comment]
It will be in 9.4.7, which is due out in the next few weeks

**Comment by blop** [comment]
Fixed in Jetty 9.4.7.v20170914

**Comment by oliver-steinbrecher** [comment]
This issue isn't solved completely because it doesn't cover DELETE Methods. We're sending an `HTTP DELETE /path/{id}`  and put the revision into the  `If-Match` Header. The gzip-handler doesn't removed the `--gzip` suffix in that case.

**Comment by oliver-steinbrecher** [comment]
Can we reopen this issue then ?

**Comment by gregw** [comment]
Yes, but we just missed 9.4.8 release.

**Comment by gregw** [comment]
Finally fixed this. sorry for the delay.  It has also missed the recent 9.4.9 release staging, so will only be in 9.4.10

**Comment by oliver-steinbrecher** [comment]
Awesome ! Thanks for solving this.
