### ISSUE TITLE
NPE when constructing subclasses of ExecutorThreadPool

### ISSUE THREAD

**Issue by nicktrav** [eclipse/jetty.project#2464]
When updating from 9.4.8 to 9.4.9, we're running into an NPE when instantiating subclasses of `ExecutorThreadPool`, which was recently refactored in a272fb6e391e126bbdd851bccfc6bde25870570e.

It looks like the problem here is that the `ExecutorThreadPool` constructor is instantiating a new instance of `ThreadPoolBudget` before it has itself been fully constructed. This, in turn, calls `#getMinThreads` on our subclass, which, in our case, refers to an instance variable that hasn't been initialized yet.

`ExecutorThreadPool`:
```java
private ExecutorThreadPool(ThreadPoolExecutor executor, int minThreads, int reservedThreads, ThreadGroup group)
{
    int maxThreads = executor.getMaximumPoolSize();
    if (maxThreads < minThreads)
    {
        executor.shutdownNow();
        throw new IllegalArgumentException("max threads (" + maxThreads + ") cannot be less than min threads (" + minThreads + ")");
    }
    _executor = executor;
    _executor.setThreadFactory(this::newThread);
    _budget = new ThreadPoolBudget(this);
    _group = group;
    _minThreads = minThreads;
    _reservedThreads = reservedThreads;
}
```

`ThreadPoolBudget`:
```java
public ThreadPoolBudget(ThreadPool.SizedThreadPool pool)
{
    this(pool,Math.min(ProcessorUtils.availableProcessors(),pool.getMinThreads()));
}
```

I've written a [minimal re-producer](https://github.com/nicktrav/jetty.project/commit/268b4497f2a2d9241027e76f35cf44e33fe168b4) that closely resembles what we are doing internally. Note that this worked in 9.4.8, when using the previously deprecated `ExecutorThreadPool`.

**Comment by nicktrav** [comment]
One obvious fix I can think of is to allow for `_budget` to be lazily instantiated outside of the constructor, so that a partially constructed `ExecutorThreadPool` object is not passed into the `ThreadPoolBudget` constructor. Happy to open a fix for that, though there might be nicer ways.

**Comment by gregw** [comment]
@nicktrav a simpler "fix" might just be to assign the _budget as the very last line in the constructor so that all other fields are initialized.... let me try that with your reproduction...

**Comment by gregw** [comment]
@nicktrav The simple fix was  to use the `ThreadPoolBudget` using the constructor that allows the `warnAt` value to be passed in rather than obtained from `getMinThreads`.   I've pushed that fix.

**Comment by nicktrav** [comment]
Thanks for the quick fix @gregw!

I'd still point out that passing `this` out of constructor like this feels a little dubious, given the `ExecutorThreadPool` still isn't fully initialized when it's being passed.

**Comment by gregw** [comment]
@nicktrav it is a little dubious, so I've reordered as well to make it slightly less dubious (but still dubious).
