### ISSUE TITLE
Require JDK 11 for Jetty 10.x

### ISSUE THREAD

**Issue by sbordet** [eclipse/jetty.project#2948]
Jetty 10.x should be based on JDK 11. 

By the time Jetty 10.x will be released, JDK 12 will be out already, JDK 8 will be unmaintained and therefore makes little sense to keep compatibility with JDK 8, let alone JDK 9 and 10 that are already unmaintained at this time.

**Comment by sbordet** [comment]
Maven PMD plugin version 3.10.0 does not work with JDK 11.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.10.0:pmd (pmd) on project jetty-util: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.10.0:pmd failed: org.apache.maven.reporting.MavenReportException: Unsupported targetJdk value '11'. -> [Help 1]
```

**Comment by sbordet** [comment]
Maven Shade plugin 3.2.0 does not work with JDK 11.

```
Caused by: java.lang.UnsupportedOperationException
    at org.objectweb.asm.ClassVisitor.visitNestHostExperimental (ClassVisitor.java:158)
    at org.objectweb.asm.commons.ClassRemapper.visitNestHostExperimental (ClassRemapper.java:185)
    at org.objectweb.asm.ClassReader.accept (ClassReader.java:541)
    at org.objectweb.asm.ClassReader.accept (ClassReader.java:391)
    at org.apache.maven.plugins.shade.DefaultShader.addRemappedClass (DefaultShader.java:466)
    at org.apache.maven.plugins.shade.DefaultShader.shadeSingleJar (DefaultShader.java:237)
    at org.apache.maven.plugins.shade.DefaultShader.shadeJars (DefaultShader.java:192)
    at org.apache.maven.plugins.shade.DefaultShader.shade (DefaultShader.java:106)
    at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute (ShadeMojo.java:442)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

See also #2941.

**Comment by joakime** [comment]
Sounds a lot like Issue #2458 as well.

**Comment by joakime** [comment]
Other "Java 11" labeled issues can be found at link: https://github.com/eclipse/jetty.project/labels/Java%2011

**Comment by sbordet** [comment]
Will try tomorrow to update to ASM 7.0-beta, which should support JDK 11.

**Comment by olamy** [comment]
pmd fixed see https://issues.apache.org/jira/browse/MPMD-271 and comments for https://issues.apache.org/jira/browse/MPMD-270

**Comment by olamy** [comment]
shade plugin https://issues.apache.org/jira/browse/MSHADE-301

**Comment by olamy** [comment]
branch created with only jdk11 jetty-10.0.x_jdk11_only

**Comment by olamy** [comment]
we need this one fixed as well https://issues.apache.org/jira/browse/MPLUGIN-336

**Comment by janbartel** [comment]
@sbordet  when you remove the profiles for alpn in jetty-10, don't forget to remove the osgi tests that verify alpn works with http2 in osgi.

**Comment by sbordet** [comment]
@janbartel we still want to test ALPN with OSGi with the Java 9+ mechanism.
I guess you're suggesting to remove only those that use the bootclasspath. Are those that contains `Boot` in the class name?

**Comment by janbartel** [comment]
@sbordet um, nope, all the tests have Boot in the name :)

The HTTP2 related ones are:

* TestJettyOSGiBootHTTP2.java   this needs the mortbay alpn-boot.jar (assume this is the one you're removing?)
* TestJettyOSGiBootHTTP2JDK9.java  this uses the jetty-alpn-java-server and jetty-alpn-server jars (not sure if this will change?)
* TestJettyOSGiBootHTTP2Conscrypt.java  I assume this one will be unchanged?

**Comment by sbordet** [comment]
@janbartel removed `TestJettyOSGiBootHTTP2`.

**Comment by sbordet** [comment]
Done.

**Comment by cowwoc** [comment]
https://issues.apache.org/jira/browse/MSHADE-302 might also be relevant (if you guys use `minimizeJar`). It's still not fixed.

**Comment by olamy** [comment]
Not sure we use it the minijar feature here.
Anyway @cowwoc thanks for the information. I was on my may releasing maven shade plugin so I need to update the jdependency dependency as well and add it test.
