### ISSUE TITLE
SSL user cert authentication with USB token

### ISSUE THREAD

**Issue by kinkylol** [eclipse/jetty.project#3131]
Hello,

We have an issue with jetty 9.3.25 regarding SSL negotiation with user cert authentication and we want to know if an update can solve the problem.
https://github.com/eclipse/jetty.project/blob/jetty-9.3.25.v20180904/jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java

Note that 
* The user certificate is stored in a USB token which loads a middleware to enter the pin when the server request the certificate.
* The issue is not present when the certificate is stored in the browser.
* Reloading the page will re-request the certificate and the authentication is successful.

Chrome is returning the error: website sent an invalid response ERR_SSL_PROTOCOL_ERROR (same behavior with Firefox)

I have tried everything from: checking the time/region in both server and client / disabling QUIC / disabling TLS 1.3 / clearing the browser cache / clearing the SSL state

Jerry is throwing the exception: 
```
javax.net.ssl.SSLHandshakeException: Closed during handshake
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:591) ~[jetty-io-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:322) [jetty-server-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:231) [jetty-server-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [jetty-io-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:259) [jetty-io-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [jetty-io-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.25.v20180904.jar:9.3.25.v20180904]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.25.v20180904.jar:9.3.25.v20180904]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```
	
Full logs here: https://cloud.wallix.com/index.php/s/Tii6RyeqPoeRbd2
as I am not sure what portion of the logs should I enclose.

I see modification for this portion of code here: https://github.com/eclipse/jetty.project/blame/jetty-9.4.14.v20181114/jetty-io/src/main/java/org/eclipse/jetty/io/ssl/SslConnection.java
(lines 548 / 549 )

and here: https://github.com/eclipse/jetty.project/issues/1228
and here: https://github.com/eclipse/jetty.project/issues/2255

In the tcpdump capture I see that:
- The server sends a TLS alert Close notify followed by a TCP FIN.
- The client then send the Certificate 

Can you please confirm if the exception is raised because the SSLEngine is closed and why.
Any help will really appreciated.

Thanks

**Comment by joakime** [comment]
Both issues #1228 and #2255 that you linked are fixed in Jetty 9.4.9 and newer.

Is there some reason you cannot update to a more recent version of Jetty?  
(The Jetty 9.3.x code line is in maintenance mode and will only be getting security fixes from here until it's declared End-of-Life)

**Comment by kinkylol** [comment]
Hi,

Thanks for the quick response. 

We will surely proceed to update. We had some issue with session management when we

**Comment by kinkylol** [comment]
Hi,

Thanks for the quick response.
We have performed an update to version 9.4.14 but the behavior is still the same.

Now two exceptions are raised:

```
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:502) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:353) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:216) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:225) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:175) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.doClose(SslConnection.java:1132) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:220) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:662) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:331) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:243) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
```


```
javax.net.ssl.SSLHandshakeException: Closed during handshake
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:549) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:331) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:243) [jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

Full logs here: https://cloud.wallix.com/index.php/s/KGWYtPiA5LAfrnY

**Comment by joakime** [comment]
Does running with `-Djavax.net.debug=ssl` on the JVM tell you anything useful as to why the handshake was closed?

**Comment by kinkylol** [comment]
I see that jetty is saying:

```
wabam-server-15, WRITE: TLSv1.2 Handshake, length = 1930
wabam-server-19, called closeOutbound()
wabam-server-19, closeOutboundInternal()
wabam-server-19, SEND TLSv1.2 ALERT:  warning, description = close_notify
wabam-server-19, WRITE: TLSv1.2 Alert, length = 2
wabam-server-15, called closeOutbound()
wabam-server-15, closeOutboundInternal()
```

* Server CN is x509.local12.moh (with an subjectAltName x509.sub.local12.moh)
* Note that the client certificat CN is not found in this logs
full logs are here: https://cloud.wallix.com/index.php/s/c5FSkH23mfcacxT

```
*** ServerHelloDone
wabam-server-15, WRITE: TLSv1.2 Handshake, length = 1930
wabam-server-19, called closeOutbound()
wabam-server-19, closeOutboundInternal()
wabam-server-19, SEND TLSv1.2 ALERT:  warning, description = close_notify
wabam-server-19, WRITE: TLSv1.2 Alert, length = 2
wabam-server-15, called closeOutbound()
wabam-server-15, closeOutboundInternal()
wabam-server-15, SEND TLSv1.2 ALERT:  warning, description = close_notify
wabam-server-15, WRITE: TLSv1.2 Alert, length = 2
Using SSLEngineImpl.
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1.1
wabam-server-16, READ: TLSv1 Handshake, length = 210
*** ClientHello, TLSv1.2
RandomCookie:  GMT: -1601850061 bytes = { 145, 237, 11, 102, 222, 234, 2, 114, 222, 249, 31, 80, 214, 116, 107, 93, 104, 131, 224, 135, 204, 102, 203, 76, 69, 130, 153, 106 }
Session ID:  {}
Cipher Suites: [Unknown 0x3a:0x3a, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, Unknown 0xcc:0xa9, Unknown 0xcc:0xa8, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA]
Compression Methods:  { 0 }
Unsupported extension type_2570, data: 
Extension renegotiation_info, renegotiated_connection: <empty>
Extension server_name, server_name: [type=host_name (0), value=x509.sub.local12.moh]
Unsupported extension type_23, data: 
Unsupported extension type_35, data: 
Extension signature_algorithms, signature_algorithms: SHA256withECDSA, Unknown (hash:0x8, signature:0x4), SHA256withRSA, SHA384withECDSA, Unknown (hash:0x8, signature:0x5), SHA384withRSA, Unknown (hash:0x8, signature:0x6), SHA512withRSA, SHA1withRSA
Unsupported extension status_request, data: 01:00:00:00:00
Unsupported extension type_18, data: 
Unsupported extension type_16, data: 00:0c:02:68:32:08:68:74:74:70:2f:31:2e:31
Unsupported extension type_30032, data: 
Extension ec_point_formats, formats: [uncompressed]
Extension elliptic_curves, curve names: {unknown curve 31354, unknown curve 29, secp256r1, secp384r1}
Unsupported extension type_27, data: 02:00:02
Unsupported extension type_43690, data: 00
***
%% Initialized:  [Session-45, SSL_NULL_WITH_NULL_NULL]
%% Invalidated:  [Session-45, SSL_NULL_WITH_NULL_NULL]
matching alias: wabam-cert-custom
Standard ciphersuite chosen: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
%% Negotiating:  [Session-45, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA]
*** ServerHello, TLSv1.2
RandomCookie:  GMT: 1526029232 bytes = { 138, 228, 1, 85, 250, 61, 237, 101, 116, 121, 196, 218, 73, 89, 100, 157, 171, 91, 32, 183, 200, 246, 141, 154, 83, 74, 207, 182 }
Session ID:  {91, 245, 92, 176, 223, 162, 21, 90, 52, 31, 247, 168, 61, 65, 228, 51, 100, 26, 113, 80, 130, 234, 172, 166, 149, 68, 181, 139, 221, 29, 17, 173}
Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
Compression Method: 0
Extension renegotiation_info, renegotiated_connection: <empty>
***
Cipher suite:  TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
*** Certificate chain
chain [0] = [
[
  Version: V3
  Subject: CN=x509.local12.moh, O=Wallix, L=Paris, ST=IDF, C=FR
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 2048 bits
  modulus: 23921587722431471609285984403851251866305563259360452848921550823882362210341520965857730647018683156267261303107298711498876269718917972046236985779698142485861515221579007068968032861612182415552174403446001948392924630361534084751812487517905357589193914156712529439229626302343436405452304101705210633398304800374463656672610577058655445811381040370305712744271262527957011059160365195977316755590558682809192539761759883205564052185973024881631445591302605610930376232521650829754700329945210224722324559846216044955733113781043012411196059343057776079492441712809158252349977528734541596572175353669838837012033
  public exponent: 65537
  Validity: [From: Fri Nov 16 10:37:17 CET 2018,
               To: Wed May 15 11:37:17 CEST 2019]
  Issuer: CN=local12.moh, OU=Support, O=Wallix, L=Paris, ST=IDF, C=FR
  SerialNumber: [    9b5944c6 e0da7a5f]

Certificate Extensions: 3
[1]: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  serverAuth
]

[2]: ObjectId: 2.5.29.15 Criticality=false
KeyUsage [
  Key_Encipherment
  Data_Encipherment
]

[3]: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: x509.local12.moh
  DNSName: x509.sub.local12.moh
]
```

**Comment by kinkylol** [comment]
Please find a more readable logs as I had elasticsearch flooding:
https://cloud.wallix.com/index.php/s/c5FSkH23mfcacxT

```
***
*** ECDH ServerKeyExchange
Signature Algorithm SHA256withRSA
Server key: Sun EC public key, 256 bits
  public x coord: 6901711003871266815636287129901535509622598328331529870047841661829038387184
  public y coord: 57807806029299254137982007936629119368039698711976360335434317503320378262815
  parameters: secp256r1 [NIST P-256, X9.62 prime256v1] (1.2.840.10045.3.1.7)
*** CertificateRequest
Cert Types: RSA, DSS, ECDSA
Supported Signature Algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA256withDSA, SHA224withECDSA, SHA224withRSA, SHA224withDSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA
Cert Authorities:
<Empty>
*** ServerHelloDone
wabam-server-15, WRITE: TLSv1.2 Handshake, length = 1930
Scheduler-1624972302, called closeOutbound()
Scheduler-1624972302, closeOutboundInternal()
Scheduler-1624972302, SEND TLSv1.2 ALERT:  warning, description = close_notify
Scheduler-1624972302, WRITE: TLSv1.2 Alert, length = 48
Scheduler-1624972302, called closeOutbound()
Scheduler-1624972302, closeOutboundInternal()
Scheduler-1624972302, SEND TLSv1.2 ALERT:  warning, description = close_notify
Scheduler-1624972302, WRITE: TLSv1.2 Alert, length = 48
Scheduler-1624972302, called closeOutbound()
Scheduler-1624972302, closeOutboundInternal()
Scheduler-1624972302, SEND TLSv1.2 ALERT:  warning, description = close_notify
Scheduler-1624972302, WRITE: TLSv1.2 Alert, length = 2
Scheduler-1624972302, called closeOutbound()
Scheduler-1624972302, closeOutboundInternal()
Scheduler-1624972302, called closeOutbound()
Scheduler-1624972302, closeOutboundInternal()
wabam-server-22, called closeOutbound()
wabam-server-22, closeOutboundInternal()
```
and the error on Chrome is raised after these logs

**Comment by kinkylol** [comment]
Also here is the network traffic that shows the client sending the certificate and the server acking.
However I dont understand the Close Notify send by the server in the capture and the logs above.

![selection_011](https://user-images.githubusercontent.com/674077/48847606-43a26080-eda2-11e8-8f2d-9bf2059acc70.png)

**Comment by kinkylol** [comment]
Hello,

we tried to investigate some more in our application but had not much success so far. Would you have, by any chance, encountered some similar issue during your tests with SSL connection since last November ?

Thanks again for any lead your might provide us on this.
