### ISSUE TITLE
HttpURI parsing of path params is bad

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.project#405]
These flaws were identified at the HttpServletRequest side in Issue #222

HttpURI parsing of an input like this ...

```
/path/info;a=b/foo;c=d
```

Will not find both params, only `c=d` is returned from `HttpURI.getParam()`.

Should `getParam()` return `a=b,c=d` ?  (This result seems just as bad, as you have no way to know which path segment each param appeared in.

Also, there appears to be no method to obtain the parameter-less path, such that the result of such a method would return `/path/info/foo` for the above example,

**Comment by gregw** [comment]
I believe it is correct for HttpURI to return the parameters in the path, as according to [the RFC](https://tools.ietf.org/html/rfc3986#section-3.3) parameters are opaque to the general syntax of a URI and are thus part of each segment.

So still thinking as to where these should be stripped out? perhaps canonical path?

**Comment by gregw** [comment]
dang! that's not right as we do parse out the last param.... thinking....

**Comment by gregw** [comment]
Already handed in getDecodedPath, so that you get results like:
````
requestURI=/dump/foo;x=y/info;a=1/bar;p=q
contextPath=
servletPath=/dump
pathInfo=/foo/info/bar
````

**Comment by drobert** [comment]
I'm not sure I understand why this was closed or what the resolution was. A direct comparison of the current release of Jetty vs Tomcat for example will yield very different results for `getServletPath()` on a request containing matrix variables. For example, given the request /some/path;foo=bar,baz=qux/here with context "" (root context) and a servlet mapped to `/*`, the results of calling `request.getServletPath()` are:

- Tomcat: /some/path/here
- Jetty: /some/path

I'm not sure if the spec is particularly clear on how this should work, but this does have implications for frameworks like springmvc within spring boot, where @RequestMapping annotations involving matrix variables will fail to match in jetty but will match in tomcat (ticket in SPR pending).

Is the resolution here "there is no bug, just a disagreement vs tomcat on what getServletPath() means?"

**Comment by gregw** [comment]
@drobert I ran a test in the jetty 9.3.x branch and generated the output I listed above, which indicates that the params are correctly stripped out.

You can see in the code that when [Request.setMetaData](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L1722) is called that it uses [getDecodedPath](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-util/src/main/java/org/eclipse/jetty/util/URIUtil.java#L274) to strip off the parameters.

This was changed in 2014!  So what version of Jetty are you using?

**Comment by gregw** [comment]
This was changed in 7f62f2600b943b9aed0e4771891939bf61372c5a  and I just committed 		cf6c15d to verify that it still working

**Comment by drobert** [comment]
I believe my comments to be more directly relevant to #222, but as that was closed in reference to this ticket, I'll leave them here. My apologies if I'm misunderstanding the resolution of this ticket.

I'm currently testing using jetty-server-9.2.16.v20160414 (I have a recent version of 9.3 I'm trying against as well; I'll post results when I'm able).

I'm making a request against to a webapp running in the root context with uri: /en/user/location;type=10004,10014,10006,10015/header/x-akamai-edgescape

By the time my application begins processing the request, I have:
org.eclipse.jetty.server.Request:
* _contextPath: ""
* _pathInfo: null
* _requestURI: /en/user/location;type=10004,10014,10006,10015/header/x-akamai-edgescape
* _servletPath: /en/user/location

I'm seeing a few places these values are parsed/set, including:

- Server.handle() populates a `target` variable via `connection.getRequest().getPathInfo()` which holds value `"/en/user/location"`. This ultimately ends up in `JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.doScope()` which calls `baseRequest.setServletPath(servlet_path)` (line 489) with value `/en/user/location`
- `org.eclipse.jetty.server.HttpChannel.startRequest()` parses `path_info` from the request via `URIUtil.canonicalPath(path)` again with value `/en/user/location`

So, any way I get into my application, `getServletPath()` behaves as described in #222. So, it may be the case that HttpURI parsing is working correctly via this ticket, but something about the way the request and the underlying utilities are interacting is not giving me the expected results at the application level after they're all wired together.

**Comment by drobert** [comment]
Ok, I stand somewhat corrected. Using Jetty 9.3.8.v20160314 pathInfo and servletPath are correctly parsing the servletPath and pathInfo. 

So I suppose the bug remains in the 9.2x line. But my comments about the 'latest' version are inaccurate.

**Comment by gregw** [comment]
I'm not really keen on continuing to develop 9.2.x, which is almost EOL.   But if there is a big springboot use-case, we can consider.   Can you say why 9.2.x is needed?

**Comment by drobert** [comment]
I can't. The version of spring boot we're on doesn't support 9.3 due to some api changes with GZip handling and some of our jetty embedded server customizations involve files that are not forwards-compatible. The latest spring boot version negates most of this, so it's not a show-stopper.

I only brought most of this up because, due to our version of 9.2 being released so recently, it seemed like this was still an issue in supported versions. Coupled with #222 being closed with so little ceremony, I was just noting that in a seemingly actively supported product line, this bug is still "open". I'm ok with "won't fix, upgrade to 9.3" for my personal use cases, however.
